// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Converter from "./Converter.bs.js";
import * as ConsultingForm from "./ConsultingForm.bs.js";
import * as ConsultingRates from "./ConsultingRates.bs.js";

function App(Props) {
  var callback = function (rates, error) {
    console.log(rates, error);
    
  };
  var match = React.useState(function () {
        return {
                value: 1000,
                currency: /* USD */0,
                duration: /* Hourly */0
              };
      });
  var setRate = match[1];
  var onSubmit = function (values) {
    Curry._1(setRate, (function (_prev) {
            return values;
          }));
    console.log(values);
    
  };
  Converter.fetchCurrencyExchangeRates("USD", ["INR"], callback);
  return React.createElement("div", {
              className: "bg-blue-50 w-full flex justify-center items-center py-8 h-screen"
            }, React.createElement("div", {
                  className: "w-11/12 p-12 sm:w-8/12 md:w-6/12 lg:w-1/2  \n        mx-auto py-10 bg-white flex-col justify-center items-center rounded-3xl shadow hover:shadow-md duration-4 min-h-1/2"
                }, React.createElement("header", {
                      className: "flex flex-column justify-center self-center h-24"
                    }, React.createElement("h2", {
                          className: "p-2.5 text-blue-500 text-3xl"
                        }, "Rate Calculator")), React.createElement("div", {
                      className: "md:grid md:grid-cols-2 md:gap-12"
                    }, React.createElement(ConsultingForm.make, {
                          onSubmit: onSubmit
                        }), React.createElement(ConsultingRates.make, {
                          rate: match[0]
                        }))));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
