// Generated by ReScript, PLEASE EDIT WITH CARE


var supportedCurrencies = [
  /* USD */0,
  /* INR */1
];

var supportedDurations = [
  /* Hourly */0,
  /* Daily */1,
  /* Weekly */2,
  /* Monthly */3,
  /* Yearly */4
];

export {
  supportedCurrencies ,
  supportedDurations ,
  
}
/* No side effect */
